### ISSUE TITLE
Some syntax choices throw bad API error

### ISSUE THREAD

**Issue by Aecasorg** [jonluca/PasteBinApp#11]
Some syntax choices throw "Bad API request, invalid api_paste_format" errors when submitting/posting to pastebin. 

Seems some syntax choices don't seem to match the Pastebin API format. E.g. '6502 TASM/64TASS' should be '6502tasm' when posting API.

**Comment by jonluca** [comment]
I'm not sure about that weird bad api request bug. The api found here https://pastebin.com/api lists all the valid syntaxes. I've done some simple debugging but couldn't get it to fail. What's a language that fails for you?

**Comment by Aecasorg** [comment]
Ah, yes. The only way for the bug to come is if you have set the incorrect syntax in the options menu. It is not enough with setting syntax in pasteview (that is something else that needs rectifying...). Try 'None' or '6502 TASM/64TASS', and it should show up. 

I think we need to make the whole list as a dictionary with the correct API version linked, kinda like what was done with the Pastebin --> Highlightr syntax list.

**Comment by jonluca** [comment]
This bug is fixed right?

**Comment by Aecasorg** [comment]
Indeed!
