### ISSUE TITLE
Save list of completed pastes

### ISSUE THREAD

**Issue by jonluca** [jonluca/PasteBinApp#2]
A great (and much needed) addition is to have a local list of saved previous pastes. 

- [ ] Create new view in storyboard for past pastes
- [ ] Implement logic to save links from pastes
- [ ] Make sure you can copy and paste the links from the list 
- [ ] Save links locally to device and sync with iCloud

**Comment by Aecasorg** [comment]
Hi, 
This might be a stupid question, but would you like the list of previous pastes to be both of the paste itself and the link connected to it, or just the links? One's obviously easier to do than the other ;)
Regards, 
Henrik

**Comment by jonluca** [comment]
Hi Henrik! 

I was just thinking the list of links to previous pastes. You can retrieve the contents by just following the links, so just a list of links would be fine! 

Should be a fairly trivial addition - keep a local array, and just push the results of the api call every time. Then add a new list view controller and fill it in with the results, and have it copy the contents of any entry on click.

Thanks for looking at this!

**Comment by Aecasorg** [comment]
OK, thanks and you're welcome!

Yeah, seems easy enough, though you have to bear with me as I work 7 days/week (not coding) so it'll be slow progress. Looking forward to it though!

**Comment by jonluca** [comment]
@Aecasorg Update should be live, closing this issue now. Thanks again!
