### ISSUE TITLE
Syntax Search

### ISSUE THREAD

**Issue by jonluca** [jonluca/PasteBinApp#7]
Be able to fuzzy-search through all the syntax options, so we don't need to scroll down. 

[This might be a good library](https://cocoapods.org/pods/FuzzySearch)

We'd just add a text input at the top of the syntax search list, and have it filter based on the fuzzy search results.

**Comment by Aecasorg** [comment]
What do you want to be done with the syntax selector in the Options Menu? Leave it as it is or add search capability there as well? It probably won't be changed as often as in the popup syntax selector in paste view.

**Comment by jonluca** [comment]
I definitely think we should have a way of filtering it in the options menu. There are so many options that it's bad UX to make a user scroll 3 or 4 times through their screen without some form of "shortcut" to get to where they want. I think a text filter would be ideal.

**Comment by Aecasorg** [comment]
I agree. 

Which option would you like?
- A textfield search on top of the existing list that's already implemented in the Options Menu.
- The existing syntax search popup (with search textfield) ported over from the paste view.
- A simple textfield search directly on the Options Menu view without segueing into a list/popup.

**Comment by jonluca** [comment]
I think the best option would be to just have the selection view where you can scroll through all the options be exactly the same as it is now, just with a text field at the top that automatically filters the results.
